### ISSUE TITLE
Weapon Keys Don't Work

### ISSUE THREAD

**Issue by edthebat** [MajorCooke/MC_Utility#2]
KEYCONF Buster allows for cycling through weapons with the 'next weapon' and 'previous weapon' commands (commonly set to the mouse wheel by many users and commercial FPS games), but the weapon slot keys (default, 1 through 0 on the top row) do not work at all.

**Comment by MajorCooke** [comment]
What are you testing it with? Did you make sure to load it first?
And did you make sure to test this with the base alone, and NOT with yours?

**Comment by edthebat** [comment]
Yes, I loaded it first. Testing it with any other project that uses KEYCONF setslot, and any third project that includes weapons not defined with setslot. And yes, I tested with the base, NOT with mine. Mine did nothing to change anything except what you see in the pull request, which had nothing to do with key commands

**Comment by edthebat** [comment]
Have just confirmed the issue is present even if no other files are loaded. mc_utility by itself, with KEYCONF Buster turned on, will disable the weapon keys

**Comment by MajorCooke** [comment]
If you're testing this with [standard Doom weaponry](https://github.com/coelckers/gzdoom/blob/master/wadsrc/static/zscript/actors/doom/weaponssg.zs), that's because slotpriority and slotnumber are not assigned onto the weapons. Nothing can be done about that.

**Comment by MajorCooke** [comment]
[All the weapons are assigned on the player itself](https://github.com/coelckers/gzdoom/blob/master/wadsrc/static/zscript/actors/doom/doomplayer.zs#L21). It won't work with anything that doesn't have a slot number/priority assigned. That's why I included keyconf buster toggle option.

**Comment by edthebat** [comment]
I've just tested with a custom weapon that does have Weapon.Slotnumber and Weapon.Slotpriority set. Weapon keys still don't work.

**Comment by MajorCooke** [comment]
[It works fine with D4D.](https://forum.zdoom.org/viewtopic.php?f=43&t=54843&p=967174#p967174) Give it a try there, just to make sure.

**Comment by edthebat** [comment]
I see the issue there, now. Combining 'unslotted' weapons with slotted ones was causing confusion.

This raises further questions, though. My pull request is intended to collect slot numbers for the weapons that don't explicitly define them, yet I still cannot use weapon keys to select them; only mousewheel. Any advice on what's still missing?

**Comment by MajorCooke** [comment]
Indeed, the defined numbers and priorities are both required. There is a reason why my system only deals with those that use them. I wish I could tell you more but the way the keyconf parsing sets up the next/previous weapons in the player (you can check the virtual functions for more info) is quite confusing. 

The weapons inside of those, if assigned by keyconf or player definition, means they don't have a slot priority. And as such, it's impossible to sort them appropriately. 

This is why Graf deprecated usage of keyconf. There's no way to properly set those up at all. The only thing you can do is provide patches for those mods which replaces them, or create a manual list on your end to make a series of listed weapons, and assign a fake slot number and priority that way. 

But to that end, I would prefer creating a special parser just for it. However, that part will require some serious planning and thought. Not something I can just pull out of a hat I'm afraid, that will take a while. But it's one of my future goals.

**Comment by MajorCooke** [comment]
Simply put, their slot numbers internally default to -1. This doesn't change when assigned by keyconf. Nor is the priority.

You must use those properties or it cannot and will not work, unless you manually maintain a list somewhere for the code to search through. To that end though you'll need to maintain every single weapon which could work as a short term solution, but the moment they change names, you have to update it each time.

Doesn't strike me as worth it honestly.

**Comment by edthebat** [comment]
I see. Well frankly, if scroll-wheeling is working, I'll definitely accept that as a partial solution. With the pull request I have open, I can currently sift through a player's full arsenal, plus weapons defined with setslot (if I wanted them), so I have access to all the weapons, which is the important thing.

**Comment by MajorCooke** [comment]
I'll take a look soon, when I get the chance. If you obliged my request with the ability to turn off that extra bits so it just does the collected, I'll be happy.

Seems like this issue is no longer one so I'm closing this.
