### ISSUE TITLE
Map Zoom via Scrollwheel is Overridden by KEYCONF Buster

### ISSUE THREAD

**Issue by edthebat** [MajorCooke/MC_Utility#3]
If KEYCONF buster is on, the scrollwheel will still attempt to change weapons when the automap is open, instead of zooming.

This scenario assumes the pre-condition that scrollwheel is bound to weapon changes in-game, and bound to map zooming in automap.

**Comment by MajorCooke** [comment]
What are your bindings for mwheelup and mwheeldown? As in, the full thing. I need both. The direct commands.

**Comment by MajorCooke** [comment]
Hmmm, I'm not sure how to handle this one honestly. The only thing I can do right now, it appears, is to make it an option to override if the automap is on or not.

Otherwise, the best thing you can do is just rebind one set of keybinds to another.

**Comment by MajorCooke** [comment]
Unfortunately there's no way to properly fix this. Only thing you can do for now is assign them to different keys.

I'll leave this open for the time being, hopefully a solution will come in the form of being able to detect keybinds with automap enabled.

**Comment by edthebat** [comment]
Fixed it.

See [commit 02586c00e32541ecb9c0530e14f1d8024893419b](https://github.com/edthebat/MC_Utility/commit/02586c00e32541ecb9c0530e14f1d8024893419b) on my fork

**Comment by MajorCooke** [comment]
Aaah, didn't know that was a thing. Make a PR and I'll merge it.
